DetailledWvW=False
WebhookURL=
MistWarriorUserToken=
ComputeCast=True
SaveAtOut=True
UpdateAvailable=False
ParseExtensions=True
SingleThreaded=False
RawTimelineArrays=True
SendEmbedToWebhook=False
OutLocation=
HtmlExternalScriptsPath=
ParsePhases=True
DPSReportUserToken=
Anonymous=False
AutoAdd=False
UploadToMistWarrior=False
SaveOutTrace=True
Outdated=False
ApplicationTraces=False
CompressRaw=False
AddPoVProf=False
ComputeDamageModifiers=True
IndentJSON=False
ComputeDamage=True
LightTheme=False
UploadToDPSReports=False
UploadToWingman=False
SaveOutJSON=True
ComputeBuff=True
AddDuration=False
SkipFailedTries=False
HtmlCompressJson=False
AutoAddPath=
SaveOutCSV=False
ComputeMechanics=True
CustomTooBig=400
PopulateHourLimit=0
AutoDiscordBatch=False
ParseMultipleLogs=False
CustomTooShort=2200
SendSimpleMessageToWebhook=False
AutoParse=False
HtmlExternalScripts=False
ParseCombatReplay=False
HtmlExternalScriptsCdn=
UpdateLastChecked=1787097814
SaveOutHTML=True
MemoryLimit=0
